#! /bin/sh

### SETTINGS ###

setxkbmap -layout latam -model deadtilde
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rate 144.0 --pos 1366x0 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1366x768 --pos 0x238 --rotate normal

### CUSTOMIZATION ###

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

### AUTOSTART ###

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
start-pulseaudio-x11
nitrogen --restore
$HOME/.config/polybar/launch.sh
pasystray

